name = "EchogramPyPlot"
uuid = "cefffc6e-22df-5efe-a096-e879be851ea5"
authors = ["Rob Blackwell <rob@robblackwell.com>"]
repo = "https://github.com/EchoJulia/EchogramPyPlot.jl.git"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
EchogramColorSchemes = "4c5cd976-4938-5223-a900-acc20a7c8507"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
